image: node:20

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_app:
  stage: build
  script:
    - ng build --configuration production
  artifacts:
    paths:
      - dist/

deploy_job:
  stage: deploy
  script:
    - echo "Deploying Angular app..."
    # এখানে তোমার server deploy command দিবে
    # যেমন: scp / ftp / rsync / docker
  only:
    - main